network:
  name: vit_cifar100
  model: /home1/xxx/workspace/OpenOOD-main/OpenOOD-main/openood/networks/ViT2.py 
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: True         # set 'True' to load pretrained model  True
  checkpoint: /home1/xxx/9_gh_workspace/OpenOOD-main/OpenOOD-main/results/pytorch_model_cifar100.bin # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
dataset:
  image_size: 224 
ood_dataset:
  image_size: 224
